[build]
  command = "npm run build"
  publish = ".next"

[context.production.environment]
  DATABASE_URL = "mongodb+srv://arnobt78:arnobt78@clusterstockly.ztxew.mongodb.net/stockly?retryWrites=true&w=majority&appName=ClusterStockly"